In [1]:
print("Hi")

Hi


Первый ноутбук

SHIFT + TAB - подсказки по синтаксису!

In [2]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [3]:
a = input()
print("a =", a)

к
a = к


In [4]:
a=[1,2,3,4,10]
print(a.pop(0))
print(a.pop())
print(a)

1
10
[2, 3, 4]


In [5]:
 def func(x, y):
        return x*y;

allo

In [6]:
func(3,4)

12

БИБЛИОТЕКА NUMPY

In [7]:
import numpy as np

In [8]:
import scipy
scipy.__version__

'1.9.1'

In [9]:
rows, cols = 100, 100
a=[(list(range(i, i + cols))) for i in range(rows)]
print(a[:20])


[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100], [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 

In [10]:
a= np.asarray(a)
a*2

array([[  0,   2,   4, ..., 194, 196, 198],
       [  2,   4,   6, ..., 196, 198, 200],
       [  4,   6,   8, ..., 198, 200, 202],
       ...,
       [194, 196, 198, ..., 388, 390, 392],
       [196, 198, 200, ..., 390, 392, 394],
       [198, 200, 202, ..., 392, 394, 396]])

In [11]:
print(a*3)

[[  0   3   6 ... 291 294 297]
 [  3   6   9 ... 294 297 300]
 [  6   9  12 ... 297 300 303]
 ...
 [291 294 297 ... 582 585 588]
 [294 297 300 ... 585 588 591]
 [297 300 303 ... 588 591 594]]


In [12]:
a= np.asarray([[1,2,3],[4,5,6]], dtype=float)
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [13]:
a.shape

(2, 3)

In [14]:
a.ndim

2

In [15]:
a.dtype

dtype('float64')

In [16]:
a.strides

(24, 8)

In [17]:
a=a.astype(int)

In [18]:
a.strides

(12, 4)

In [19]:
b = a.reshape(3,2)
a[0, 2]=-10
b

array([[  1,   2],
       [-10,   4],
       [  5,   6]])

In [20]:
b.strides

(8, 4)

In [21]:
b = a.flatten() #copy в одну строку
a[1, 1]= 300
print("a= ",a)
print("b= ",b)

a=  [[  1   2 -10]
 [  4 300   6]]
b=  [  1   2 -10   4   5   6]


In [22]:
b=b.reshape(-1,3)
b

array([[  1,   2, -10],
       [  4,   5,   6]])

In [23]:
c = a.T # or a.trampose()
a[1,0]= -20
c #отсчет по столбцам

array([[  1, -20],
       [  2, 300],
       [-10,   6]])

In [24]:
c.strides, a.strides

((4, 12), (12, 4))

In [25]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
b[np.newaxis, : ] #в двумерный

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [27]:
np.expand_dims(b, axis=0)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [28]:
b[ : , np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [29]:
b[np.newaxis, :, np.newaxis].shape #фиктивные размерности, получился трехмерный массив
#b[np.newaxis, :, np.newaxis]

(1, 10, 1)

МАССИВЫ С ОСОБЫМИ СВОЙСТВАМИ

In [30]:
np.zeros(shape=(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.zeros_like(b) #размерность как у b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [33]:
np.ones(shape=(2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [35]:
np.arange(2, 9)

array([2, 3, 4, 5, 6, 7, 8])

In [36]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [37]:
np.linspace(0, 1, 5, endpoint=True)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [38]:
a = np.array([1,2,3,4,5,6], dtype = np.float32)
b= np.asarray(a)
c= np.array(a) #копирование данных
b,c 

(array([1., 2., 3., 4., 5., 6.], dtype=float32),
 array([1., 2., 3., 4., 5., 6.], dtype=float32))

In [39]:
a[0]=0
b,c

(array([0., 2., 3., 4., 5., 6.], dtype=float32),
 array([1., 2., 3., 4., 5., 6.], dtype=float32))

In [40]:
a = np.array([1,2,3,4], dtype = np.float32)
b = np.asarray(a, dtype=np.int32)
a,b

(array([1., 2., 3., 4.], dtype=float32), array([1, 2, 3, 4]))

In [41]:
a[0]=0
a, b

(array([0., 2., 3., 4.], dtype=float32), array([1, 2, 3, 4]))

In [42]:
d = [0,1,2,3,4,5]
a=np.asarray(d)
d[0]=1
a,d

(array([0, 1, 2, 3, 4, 5]), [1, 1, 2, 3, 4, 5])

ОПЕРАЦИИ С ЭЛЕМЕНТАМИ

In [43]:
a = np.arange(10).reshape(2, -1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
a**2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]], dtype=int32)

In [45]:
a+2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [46]:
2**a

array([[  1,   2,   4,   8,  16],
       [ 32,  64, 128, 256, 512]], dtype=int32)

In [47]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [48]:
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03]])

In [49]:
np.log(1+a) #натуральный

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509]])

In [50]:
np.log2(a+1)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809]])

In [51]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]])

In [52]:
a>3

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [53]:
import random

In [54]:
np.random.seed(5656)
a = np.random.randint(0, 10, size=(7, ))
a[3]=11
a

array([ 4,  6,  7, 11,  0,  3,  5])

In [55]:
a.max(), a.argmax(), a.sum(), a.prod(), a.mean()

(11, 3, 36, 0, 5.142857142857143)

In [56]:
np.random.seed(1000)
a=np.random.randint(0, 10, size=(3,7))
a[1,3]=15
a

array([[ 3,  7,  7,  0,  1,  0,  9],
       [ 8,  9,  4, 15,  4,  4,  2],
       [ 9,  8,  2,  4,  2,  5,  5]])

In [57]:
a.max(axis=1)#максимумы построчно

array([ 9, 15,  9])

In [58]:
a.max(axis=0)#по столбцам

array([ 9,  9,  7, 15,  4,  5,  9])

In [59]:
a.argmax()

10

In [60]:
h = a.argmax()
print("i = ", h//a.shape[1], "j = ", h%a.shape[1])

i =  1 j =  3


In [61]:
np.unravel_index(np.argmax(a), a.shape)

(1, 3)

In [62]:
a=np.array([True,True,False])
a

array([ True,  True, False])

In [63]:
a.any()

True

In [64]:
a.all()

False

In [65]:
a=np.array([True,True,False])

In [66]:
a=np.array([[True,True,False],[True,False,True]])
a

array([[ True,  True, False],
       [ True, False,  True]])

In [67]:
a.any(axis=0)

array([ True,  True,  True])

In [68]:
np.logical_not(a)

array([[False, False,  True],
       [False,  True, False]])

In [69]:
~a

array([[False, False,  True],
       [False,  True, False]])

БИНАРНЫЕ ОПЕРАЦИИ

In [70]:
a=a.astype(int)
a

array([[1, 1, 0],
       [1, 0, 1]])

In [71]:
np.random.seed(1201)
b = np.random.randint(0, 10, size=(2,3))
b

array([[5, 7, 9],
       [3, 2, 4]])

In [72]:
a*b, a+b

(array([[5, 7, 0],
        [3, 0, 4]]),
 array([[6, 8, 9],
        [4, 2, 5]]))

In [73]:
np.fmax(a,b)

array([[5, 7, 9],
       [3, 2, 4]])

In [74]:
a>b

array([[False, False, False],
       [False, False, False]])

ufunc - почитать!

In [75]:
np.random.seed(123456)
a = np.random.random(size=(2,4))
b = a + np.random.random(size=(2,4))*1e-5 #10**(-5)
a

array([[0.12696983, 0.96671784, 0.26047601, 0.89723652],
       [0.37674972, 0.33622174, 0.45137647, 0.84025508]])

In [76]:
b

array([[0.12697106, 0.96672327, 0.26047974, 0.897241  ],
       [0.37675101, 0.33623034, 0.45138467, 0.8402586 ]])

In [77]:
np.isclose(a,b)

array([[ True,  True, False,  True],
       [ True, False, False,  True]])

In [78]:
np.allclose(a, b)

False

In [79]:
np.isclose(a,b).any()

True

In [80]:
a =np.array([True,True,False,True])
b =np.array([False,True,True,False])

In [81]:
np.logical_and(a,b), np.logical_or(a,b), np.logical_xor(a,b)

(array([False,  True, False, False]),
 array([ True,  True,  True,  True]),
 array([ True, False,  True,  True]))

In [82]:
a & b, a|b, a^b

(array([False,  True, False, False]),
 array([ True,  True,  True,  True]),
 array([ True, False,  True,  True]))

In [83]:
a= np.arange(30).reshape(3,-1)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [84]:
b = np.arange(a.shape[1]) #размерность как у iтого элемента массива a
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
a+b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [10, 12, 14, 16, 18, 20, 22, 24, 26, 28],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38]])

In [86]:
print("a shape = ", a.shape)
print("b shape = ", b.shape)

a shape =  (3, 10)
b shape =  (10,)


In [87]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [88]:
b = a.reshape(-1,1)
b

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [89]:
a+b

array([[ 0,  1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5,  6],
       [ 2,  3,  4,  5,  6,  7],
       [ 3,  4,  5,  6,  7,  8],
       [ 4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10]])

In [90]:
a<=b

array([[ True, False, False, False, False, False],
       [ True,  True, False, False, False, False],
       [ True,  True,  True, False, False, False],
       [ True,  True,  True,  True, False, False],
       [ True,  True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True,  True]])

In [91]:
np.array([[[1,2,3]]])+np.array([1,2,3,4,5,6]).reshape(3,2,1)

array([[[2, 3, 4],
        [3, 4, 5]],

       [[4, 5, 6],
        [5, 6, 7]],

       [[6, 7, 8],
        [7, 8, 9]]])

In [92]:
a = np.arange(20).reshape(-1,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [93]:
np.random.seed(999)
b = np.random.randint(0, 2, size=5)
b

array([0, 0, 1, 1, 0])

In [94]:
a*b

array([[ 0,  0,  2,  3,  0],
       [ 0,  0,  7,  8,  0],
       [ 0,  0, 12, 13,  0],
       [ 0,  0, 17, 18,  0]])

In [95]:
c = b[np.newaxis, :]
c

array([[0, 0, 1, 1, 0]])

In [96]:
print("b shape =", b.shape)
print("c shape =", c.shape)
print("a shape =", a.shape)

b shape = (5,)
c shape = (1, 5)
a shape = (4, 5)


In [97]:
c*a

array([[ 0,  0,  2,  3,  0],
       [ 0,  0,  7,  8,  0],
       [ 0,  0, 12, 13,  0],
       [ 0,  0, 17, 18,  0]])

<b>МАТРИЧНЫЕ ОПЕРАЦИИ</b>

In [98]:
av = np.arange(1,5).reshape(-1,2)
av

array([[1, 2],
       [3, 4]])

In [99]:
bv = np.array([[1,2],[-2,1]])
bv

array([[ 1,  2],
       [-2,  1]])

In [100]:
av*bv#поэлементно

array([[ 1,  4],
       [-6,  4]])

In [101]:
np.matmul(av, bv) #матричное умножение

array([[-3,  4],
       [-5, 10]])

In [102]:
np.dot(av, bv) #матричное умножение

array([[-3,  4],
       [-5, 10]])

In [103]:
am = np.asmatrix(av) #данные не копируются, np.matrix() данные копируются
bm = np.asmatrix(bv)
am

matrix([[1, 2],
        [3, 4]])

In [104]:
bv

array([[ 1,  2],
       [-2,  1]])

In [105]:
am*bm  #матричное умножение

matrix([[-3,  4],
        [-5, 10]])

In [106]:
av**2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [107]:
am**2 #матричное возведение в степень

matrix([[ 7, 10],
        [15, 22]])

Все для линейной алгебры:
    https://numpy.org/doc/stable/reference/routines.linalg.html

<b>ИНДЕКСАЦИЯ В ОДНОМЕРНЫХ МАССИВАХ</b>

In [108]:
a = np.arange(2, 15)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [109]:
a[0],a[4], a[len(a)-3], a[-3]

(2, 6, 12, 12)

<b>CРЕЗЫ</b>  
массив[start:finish:step]

In [110]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [111]:
variants = [a[0:5:1],a[0:5],a[:5]]
print(*map(repr, variants), sep='\n')

array([0, 1, 2, 3, 4])
array([0, 1, 2, 3, 4])
array([0, 1, 2, 3, 4])


<b>БУЛЕВА ИНДЕКСАЦИЯ (МАСКИ)</b>

In [112]:
np.random.seed(345)
a= np.random.randint(-2,7,34)
a

array([ 6, -2,  1,  6,  2,  1,  2, -1,  5,  2, -2,  4,  1,  6, -2,  1, -1,
        3,  5,  2,  3,  2, -2,  6,  3,  4,  1,  1,  2,  0,  6,  3,  0,  4])

In [113]:
a<0

array([False,  True, False, False, False, False, False,  True, False,
       False,  True, False, False, False,  True, False,  True, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [114]:
a[a<0]

array([-2, -1, -2, -2, -1, -2])

In [115]:
#кратные или 3, или 5
mask3 = a%3==0
mask5 = a%5==0
a[np.logical_or(mask3, mask5)]

array([6, 6, 5, 6, 3, 5, 3, 6, 3, 0, 6, 3, 0])

In [116]:
a[mask3 | mask5]

array([6, 6, 5, 6, 3, 5, 3, 6, 3, 0, 6, 3, 0])

<b>ИНДЕКСАЦИЯ В МНОГОМЕРНЫХ МАССИВАХ</b>

In [117]:
a = np.arange(30).reshape(5,-1)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [118]:
a[0][3], a[0,3],a[3,4]

(3, 3, 22)

In [119]:
#получить строку
a[2] #или a[2,:]

array([12, 13, 14, 15, 16, 17])

In [120]:
#получить столбец
a[:,4]

array([ 4, 10, 16, 22, 28])

In [121]:
#элементы в четных столбцах
a[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [122]:
a[0, 1::2] #нечет поз. в 0й строке

array([1, 3, 5])

In [123]:
np.random.seed(110)
a = np.random.randint(-5,5, size=(5,5))
a

array([[-5, -2,  4, -5, -5],
       [-5,  1, -3,  3,  4],
       [ 0, -5, -4, -4, -5],
       [ 3,  2,  4,  2, -4],
       [ 4, -3,  4, -4,  0]])

In [124]:
#строки в которых есть хотя бы один 0
a[(a==0).any(axis=1)]

array([[ 0, -5, -4, -4, -5],
       [ 4, -3,  4, -4,  0]])

In [125]:
a>0

array([[False, False,  True, False, False],
       [False,  True, False,  True,  True],
       [False, False, False, False, False],
       [ True,  True,  True,  True, False],
       [ True, False,  True, False, False]])

In [126]:
a[:, ((a>0).sum(axis=0))>((a<0).sum(axis=0))]

array([[ 4],
       [-3],
       [-4],
       [ 4],
       [ 4]])

In [127]:
#индексы положительных элементов
np.where(a>0)

(array([0, 1, 1, 1, 3, 3, 3, 3, 4, 4], dtype=int64),
 array([2, 1, 3, 4, 0, 1, 2, 3, 0, 2], dtype=int64))

In [128]:
#или
#Функция vstack() соединяет массивы по вертикали.
np.vstack(np.where(a>0)).T

array([[0, 2],
       [1, 1],
       [1, 3],
       [1, 4],
       [3, 0],
       [3, 1],
       [3, 2],
       [3, 3],
       [4, 0],
       [4, 2]], dtype=int64)

<b>FANCY INDEXING</b>

In [129]:
a

array([[-5, -2,  4, -5, -5],
       [-5,  1, -3,  3,  4],
       [ 0, -5, -4, -4, -5],
       [ 3,  2,  4,  2, -4],
       [ 4, -3,  4, -4,  0]])

In [130]:
#получить 1, 3 и 4 строки
a[[1, 3, 4]]

array([[-5,  1, -3,  3,  4],
       [ 3,  2,  4,  2, -4],
       [ 4, -3,  4, -4,  0]])

In [131]:
#1, 3, 4 строки и в 0 и последнем столбце
a[[1,3,4]][:,[0,-1]]

array([[-5,  4],
       [ 3, -4],
       [ 4,  0]])

In [132]:
#или (лучше)
a[np.ix_([1,3,4],[0,-1])]

array([[-5,  4],
       [ 3, -4],
       [ 4,  0]])

In [133]:
a = np.arange(12).reshape(3,-1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [134]:
a[np.ix_([0,2],[0,-1])]=1000
a

array([[1000,    1,    2, 1000],
       [   4,    5,    6,    7],
       [1000,    9,   10, 1000]])

<b>СОКРАЩЕННАЯ ИНДЕКСАЦИЯ</b>

In [135]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [136]:
#нулевой элемент из последней размерности
a[...,0]

array([[ 0,  4,  8],
       [12, 16, 20]])

In [137]:
a[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [138]:
a[...,0,:] #или a[:,0,:]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

<b>NUMPY и SCIPY: полезное</b>

*генерация случайных чисел*

In [139]:
#от 0 до 1
np.random.rand(10)

array([0.56056512, 0.0552703 , 0.82077508, 0.31679419, 0.29139348,
       0.95004879, 0.91850071, 0.58142877, 0.74637638, 0.28907766])

In [140]:
np.random.randint(1,10,5)

array([4, 9, 9, 6, 1])

In [141]:
np.random.permutation(10) #перестановка из 10 элементов

array([1, 3, 8, 0, 7, 4, 6, 5, 2, 9])

In [142]:
np.random.choice(10,size=10)

array([0, 0, 9, 5, 4, 2, 5, 6, 9, 4])

<b>СОРТИРОВКА</b>

In [143]:
np.random.seed(333)
a= np.random.choice(10,size=(3,10))
a

array([[3, 3, 6, 3, 7, 7, 6, 4, 4, 9],
       [7, 5, 5, 8, 8, 7, 3, 3, 3, 9],
       [3, 3, 7, 7, 1, 0, 8, 2, 7, 0]])

In [144]:
#sorted copy
np.sort(a.ravel())

array([0, 0, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 7, 7,
       7, 7, 7, 8, 8, 8, 9, 9])

In [145]:
a.sort(axis=0) #no copy
a

array([[3, 3, 5, 3, 1, 0, 3, 2, 3, 0],
       [3, 3, 6, 7, 7, 7, 6, 3, 4, 9],
       [7, 5, 7, 8, 8, 7, 8, 4, 7, 9]])

In [146]:
np.random.seed(333)
a= np.random.choice(10,size=(3,10))
a

array([[3, 3, 6, 3, 7, 7, 6, 4, 4, 9],
       [7, 5, 5, 8, 8, 7, 3, 3, 3, 9],
       [3, 3, 7, 7, 1, 0, 8, 2, 7, 0]])

In [147]:
a.argsort(axis=0) #сортировка индексов

array([[0, 0, 1, 0, 2, 2, 1, 2, 1, 2],
       [2, 2, 0, 2, 0, 0, 0, 1, 0, 0],
       [1, 1, 2, 1, 1, 1, 2, 0, 2, 1]], dtype=int64)

In [148]:
#уникальные элементы
np.unique(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<b>ОБЪЕДИНЕНИЕ МАССИВОВ</b>

In [149]:
from itertools import chain, zip_longest

def print_as_columns(*args, sep='\t'):
    '''print flways columns'''
    args = list(map(lambda s: s.split('\n'), args))
    width = max(map(len, chain.from_iterable(args)))
    fill = lambda s: '{:<{width}s}'.format(s, width=width)
    fillvalue = fill('')
    args = map(lambda e: map(fill, e), args)
    args = map(sep.join, zip_longest(*args, fillvalue=fillvalue))
    print(*args, sep='\n')

In [150]:
np.random.seed(987)
c = np.random.permutation(np.arange(12))
i = c.shape[0] //2
a,b=c[:i], c[i:]
a,b=a.reshape(3,2),b.reshape(3,2)
c,a,b

(array([ 1,  0,  4, 10,  5,  2,  8, 11,  6,  9,  7,  3]),
 array([[ 1,  0],
        [ 4, 10],
        [ 5,  2]]),
 array([[ 8, 11],
        [ 6,  9],
        [ 7,  3]]))

In [151]:
print_as_columns(repr(a),repr(b))
np.vstack((a,b))

array([[ 1,  0], 	array([[ 8, 11], 
       [ 4, 10], 	       [ 6,  9], 
       [ 5,  2]])	       [ 7,  3]])


array([[ 1,  0],
       [ 4, 10],
       [ 5,  2],
       [ 8, 11],
       [ 6,  9],
       [ 7,  3]])

In [152]:
np.concatenate((a,b), axis=1)

array([[ 1,  0,  8, 11],
       [ 4, 10,  6,  9],
       [ 5,  2,  7,  3]])

In [153]:
np.concatenate((a,b), axis=0)

array([[ 1,  0],
       [ 4, 10],
       [ 5,  2],
       [ 8, 11],
       [ 6,  9],
       [ 7,  3]])

In [154]:
np.hstack((a,b))

array([[ 1,  0,  8, 11],
       [ 4, 10,  6,  9],
       [ 5,  2,  7,  3]])

*подсчет расстояний между точками*

In [155]:
from scipy.spatial.distance import pdist, squareform

In [156]:
np.random.seed(2)
x = np.random.random(size=(5,2))*10
x

array([[4.35994902, 0.25926232],
       [5.49662478, 4.35322393],
       [4.20367802, 3.30334821],
       [2.04648634, 6.19270966],
       [2.99654674, 2.66827275]])

In [157]:
d= pdist(x) #пасстояние точки от всех остальных
d

array([4.24882965, 3.04809441, 6.36850901, 2.76806739, 1.66551804,
       3.90988018, 3.01487159, 3.60581275, 1.36399662, 3.6502425 ])

In [158]:
squareform(d)

array([[0.        , 4.24882965, 3.04809441, 6.36850901, 2.76806739],
       [4.24882965, 0.        , 1.66551804, 3.90988018, 3.01487159],
       [3.04809441, 1.66551804, 0.        , 3.60581275, 1.36399662],
       [6.36850901, 3.90988018, 3.60581275, 0.        , 3.6502425 ],
       [2.76806739, 3.01487159, 1.36399662, 3.6502425 , 0.        ]])

In [159]:
norm = np.linalg.norm(x,ord=2,axis=1) #нормы точекя(евклидова метрика)
norm

array([4.36765068, 7.01166475, 5.34630885, 6.52209777, 4.0123524 ])

In [160]:
squareform(pdist(x / norm[:, np.newaxis])) #нормированное расстояние

array([[0.        , 0.60100386, 0.59738254, 1.12286613, 0.65576135],
       [0.60100386, 0.        , 0.00379567, 0.5736246 , 0.05767299],
       [0.59738254, 0.00379567, 0.        , 0.57725977, 0.06146698],
       [1.12286613, 0.5736246 , 0.57725977, 0.        , 0.51813609],
       [0.65576135, 0.05767299, 0.06146698, 0.51813609, 0.        ]])

In [161]:
pdist(x, metric='cosine') #косинусовая метрика

array([1.80602821e-01, 1.78432952e-01, 6.30414171e-01, 2.15011473e-01,
       7.20354434e-06, 1.64522591e-01, 1.66308713e-03, 1.66614418e-01,
       1.88909475e-03, 1.34232502e-01])

In [163]:
S = np.array([[1,"a",2], [3, "b", 4]])
d = S[:, 1] == "a"
d

array([ True, False])